services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports: 
      - 27017:27017
    volumes: 
      - mongo_volumes:/data
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
  mongo-express: 
    image: mongo-express
    container_name: mongo_express
    ports: 
      - 8081:8081
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=user
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: unless-stopped
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: currency_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mongo_volumes: {}
  mysql_data: {}
  